// Requires Playwright and a running static preview. No runtime dependency for the site.
const assert=require('node:assert/strict');const {chromium}=require('playwright');
const base=process.env.C_PREVIEW_URL || 'http://127.0.0.1:8765/design-c.html';
(async()=>{const b=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || 'chrome',args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1440,height:1000}});const requests=[];let active=0,maxActive=0;const pending=new Set();const errors=[];p.on('pageerror',e=>errors.push(String(e)));p.on('request',r=>{if(r.url().endsWith('.mp4')){requests.push(r.url());pending.add(r);active++;maxActive=Math.max(active,maxActive)}});for(const event of ['requestfinished','requestfailed'])p.on(event,r=>{if(pending.delete(r))active--});const cdp=await p.context().newCDPSession(p);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:60,downloadThroughput:625000,uploadThroughput:125000});await p.goto(base);await p.waitForTimeout(3000);assert.equal(requests.length,2,'Only first two previews prefetched at top');assert.equal(maxActive,2);assert(await p.locator('video').evaluateAll(vs=>vs.every(v=>v.paused)),'Nothing plays offscreen');
const first=p.locator('video').first();await first.evaluate(v=>scrollTo({top:scrollY+v.getBoundingClientRect().top-innerHeight-350,behavior:'instant'}));await p.waitForFunction(()=>document.querySelector('video').readyState>=3);assert(await first.evaluate(v=>v.paused));await first.evaluate(v=>scrollTo({top:scrollY+v.getBoundingClientRect().top-150,behavior:'instant'}));await p.waitForFunction(()=>!document.querySelector('video').paused);const t=await first.evaluate(v=>v.currentTime);await p.waitForTimeout(250);assert(await first.evaluate(v=>v.currentTime)>t);
const button=p.locator('.motion').first().locator('.play-control');await button.click();assert(await first.evaluate(v=>v.paused));await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await first.evaluate(v=>scrollTo({top:scrollY+v.getBoundingClientRect().top-150,behavior:'instant'}));await p.waitForTimeout(150);assert(await first.evaluate(v=>v.paused),'Manual pause persists');await button.click();await p.waitForFunction(()=>!document.querySelector('video').paused);
const scrub=p.locator('.clip-tools input').first();await scrub.fill('2');await p.waitForFunction(()=>Math.abs(document.querySelector('video').currentTime-2)<.1);assert(await first.evaluate(v=>v.paused));await p.locator('.clip-tools button').first().click();await p.waitForFunction(()=>!document.querySelector('video').paused&&document.querySelector('video').currentTime<1);
await p.locator('#animal-study').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.waitForFunction(()=>[...document.querySelectorAll('#animal-study video')].every(v=>v.readyState>=3));await p.locator('#worlds').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.waitForTimeout(300);const animalGallery=p.locator('#worlds .world').nth(2);await animalGallery.evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.waitForFunction(()=>document.querySelectorAll('#worlds video')[2].readyState>=3);assert.equal(requests.filter(url=>/\/animals(?:-desktop)?\.mp4$/.test(url)).length,1,'Repeated clip shared across sections');
await p.locator('#motion-master').click();assert(await p.locator('video').evaluateAll(v=>v.every(x=>x.paused)));
await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});assert(await p.locator('video').evaluateAll(v=>v.every(x=>x.paused)));
const reduced=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let reducedRequests=0;reduced.on('request',r=>{if(r.url().endsWith('.mp4'))reducedRequests++});await reduced.goto(base+'#tools');await reduced.waitForTimeout(400);assert.equal(reducedRequests,0,'Reduced motion does not download speculative videos');await reduced.locator('.motion').first().scrollIntoViewIfNeeded();await reduced.locator('.motion .play-control').first().click();await reduced.waitForFunction(()=>!document.querySelector('video').paused);assert.equal(reducedRequests,1);
const data=await b.newPage({viewport:{width:390,height:844}});await data.addInitScript(()=>Object.defineProperty(navigator,'connection',{value:Object.assign(new EventTarget(),{saveData:true,effectiveType:'4g'})}));let dataRequests=[];data.on('request',r=>{if(r.url().endsWith('.mp4'))dataRequests.push(r.url())});await data.goto(base);await data.waitForTimeout(400);assert.equal(dataRequests.length,0);await data.locator('.motion').first().scrollIntoViewIfNeeded();await data.locator('.motion .play-control').first().click();await data.waitForFunction(()=>!document.querySelector('video').paused);assert(dataRequests[0].includes('-mobile.mp4'));assert.equal(dataRequests.length,1);assert(!(await data.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
const nojs=await b.newPage({javaScriptEnabled:false});await nojs.goto(base);assert.equal(await nojs.locator('.motion>.motion-poster').count(),25);assert.equal(await nojs.locator('video[src]').count(),0);
const retry=await b.newPage({viewport:{width:1440,height:1000}});let fail=true;await retry.route('**/02-timer-app*.mp4',route=>fail?route.fulfill({status:503,body:'test unavailable'}):route.continue());await retry.goto(base+'#tools');await retry.waitForFunction(()=>document.querySelector('.play-control').textContent.includes('Retry'));fail=false;await retry.locator('.motion').first().scrollIntoViewIfNeeded();await retry.locator('.play-control').first().click();await retry.waitForFunction(()=>!document.querySelector('video').paused);assert(await retry.locator('.media-error').first().isHidden());
assert.equal(errors.length,0);assert(maxActive<=2,'Download concurrency exceeded two');console.log(JSON.stringify({passed:true,maxConcurrent:maxActive,initialDownloads:2,errors,checks:['nearby preload before visible','visible playback only','user pause persists','scrub/replay','shared repeated clips','master pause','hidden tab pause','reduced motion opt-in','Save-Data opt-in and mobile file','no-JS posters','failed download and retry']},null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
